export const skills: SkillRecord[] = [
  {
    id: "skill-1",
    title: "Write Code",
    slug: "write-code",
    description: "Generate boilerplate code, refactor existing implementations, and create reusable utilities for common tasks.",
    category: "Development",
    tags: ["code", "automation", "productivity"],
    installCommand: "npm install @skild/write-code",
    createdAt: "2026-06-01T12:00:00.000Z",
    authorClerkId: "auth_12345",
    authorEmail: "author@example.com",
  },
  {
    id: "skill-2",
    title: "Review Pull Request",
    slug: "review-pull-request",
    description: "Analyze diffs, highlight potential issues, and suggest improvements for pull request submissions.",
    category: "Collaboration",
    tags: ["review", "git", "quality"],
    installCommand: "npm install @skild/review-pull-request",
    createdAt: "2026-06-05T09:30:00.000Z",
    authorClerkId: "auth_54321",
    authorEmail: "reviewer@example.com",
  },
  {
    id: "skill-3",
    title: "Summarize Documents",
    slug: "summarize-documents",
    description: "Summarize long-form content into concise bullet points for fast reading and decision-making.",
    category: "Productivity",
    tags: ["summary", "documents", "ai"],
    installCommand: "npm install @skild/summarize-documents",
    createdAt: "2026-06-10T15:20:00.000Z",
    authorClerkId: null,
    authorEmail: null,
  },
  {
    id: "skill-4",
    title: "Generate Tests",
    slug: "generate-tests",
    description: "Create unit and integration tests from code snippets to help validate behavior and catch regressions.",
    category: "Testing",
    tags: ["tests", "coverage", "qa"],
    installCommand: "npm install @skild/generate-tests",
    createdAt: "2026-06-12T08:45:00.000Z",
    authorClerkId: "auth_98765",
    authorEmail: "tester@example.com",
  },
  {
    id: "skill-5",
    title: "Deploy App",
    slug: "deploy-app",
    description: "Automate deployment workflows for web applications across staging and production environments.",
    category: "Operations",
    tags: ["deploy", "devops", "ci/cd"],
    installCommand: "npm install @skild/deploy-app",
    createdAt: "2026-06-13T18:10:00.000Z",
    authorClerkId: "auth_24680",
    authorEmail: "ops@example.com",
  },
];
