# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(data:
  {clerkId: "user_3EWC3dbi3klfskIzhEDv0KzUKm8",
   email: "killengary37@gmail.com",
   imageUrl: "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NJQkR0T3FmWU9SUFl0dHh2MHo3aXgxRi1vVFRNSGhIYjhVOXQyejJja0c1cVp2QlBVPXMxMDAwLWMiLCJzIjoiZFZBRHRET1lLeVowNHVIWEZ6Zy8wdHJOVEdhTjdiM3BwQUdGUTRHTzNSUSJ9",
   username: "garykillen"})
}